# Generated by Django 4.1.5 on 2023-03-22 17:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('penyewaanApp', '0002_alter_penyewa_blok_alter_penyewa_limit_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='penyewa',
            name='blok',
            field=models.CharField(choices=[('BLOK A', 'a'), ('BLOK B', 'b'), ('BLOK C', 'c'), ('BLOK D', 'd')], max_length=10),
        ),
        migrations.AlterField(
            model_name='penyewa',
            name='limit',
            field=models.CharField(choices=[('1 Bulan', '1'), ('2 Bulan', '2'), ('3 Bulan', '3'), ('4 Bulan', '4'), ('5 Bulan', '5'), ('1/2 Tahun', '1/2'), ('1 Tahun', '1th')], max_length=10),
        ),
        migrations.AlterField(
            model_name='penyewa',
            name='tipe',
            field=models.CharField(choices=[('RUKO', 'R'), ('TOKO', 'T')], max_length=5),
        ),
    ]
