# Generated by Django 4.1.5 on 2023-03-22 17:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('penyewaanApp', '0003_alter_penyewa_blok_alter_penyewa_limit_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='penyewa',
            name='blok',
            field=models.CharField(choices=[('BLOK A', 'BLOK A'), ('BLOK B', 'BLOK B'), ('BLOK C', 'BLOK C'), ('BLOK D', 'BLOK D')], max_length=10),
        ),
        migrations.AlterField(
            model_name='penyewa',
            name='limit',
            field=models.CharField(choices=[('1 Bulan', '1 Bulan'), ('2 Bulan', '2 Bulan'), ('3 Bulan', '3 Bulan'), ('4 Bulan', '4 Bulan'), ('5 Bulan', '5 Bulan'), ('1/2 Tahun', '1/2 Tahun'), ('1 Tahun', '1 Tahun')], max_length=10),
        ),
        migrations.AlterField(
            model_name='penyewa',
            name='tipe',
            field=models.CharField(choices=[('RUKO', 'RUKO'), ('TOKO', 'TOKO')], max_length=5),
        ),
    ]
